baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Pixaful Version 2"
[[menu.mainmenu]]
name = "Google"
parent = "Home"
url = "https://www.google.com"
weight = 1
[[menu.mainmenu]]
identifyer = "home"
name = "Home"
url = "/"
weight = 1
[[menu.mainmenu]]
identifyer = "Blog"
name = "Blog"
url = "/blog"
weight = 2
[params]
cloudinary_base_url = "https://res.cloudinary.com/pixaful/image/upload"
uglyurls = true
url = "blogs/tempus"
[permalinks]
post = ":filename"
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
cache-control = "\tmax-age=0,\n\tno-cache,\n\tno-store,\n\tmust-revalidate"
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=604800"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
